name: CI

on:
  push:
    branches: [ "feat/#128v2" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with no Tests
        run: ./gradlew build -x test

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build

  check-build:
      runs-on: ubuntu-latest
      needs: build-and-test
      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v2
          with:
            name: build-artifacts
            path: build-artifacts

        - name: Check Build Success
          run: ./gradlew -p build-artifacts check